sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t therealjaygray/docker-playground -f Dockerfile.dev .

script:
  - docker run -e CI=true therealjaygray/docker-playground npm run test


